### PR TITLE
Typings version upgrade

### PR DESCRIPTION
**Pull request by jabrythehutt**
These are my changes:
- Upgraded to the latest version of typings which now uses 'globalDependencies' rather than 'ambientDependencies'.
- Modified to be 'publishable' as an npm module (and published under @djabry/aws-sdk-typescript).
- Removed generated code.
- Added some missing modules after merging your latest changes.

### CODE REVIEW

**Comment by jabrythehutt** [comment]
I've started a readme including instructions on installing directly from github using typings.

**Comment by StefH** [comment]
This looks nice.
@ingenieux / @aldrinleal please take time to merge this one. Else your whole project doesnt add any value if it cannot be used.

@djabry I'll try to get your version an resolve some conflicts with main branch.

**Comment by jabrythehutt** [comment]
@StefH The purpose of my fork is to enable installation with Typescript 2 and npm (without typings). I've added both installation methods to my readme file but the final .d.ts files should be the same. 

I think it is possible to have one project that does both but merging my changes without refactoring would not achieve this - so perhaps only merging my readme file would be helpful for this version.

**Comment by jabrythehutt** [comment]
I've created a new branch (typings) in my forked repo that closely matches your repo with the relevant readme file

**Pull request closed without merging**
